# ===========================================================================
# Project:   InzenWireframe
# Copyright: ©2010 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :all, :required => :sproutcore
config :inzen_wireframe, :preferred_language => :en, :build_languages => [:en]
 