#!/bin/sh

# chkconfig: - 97 07
# description: Donomo Database Initialization

source /etc/rc.d/init.d/functions

workdir=/home/donomo
logfile=/var/log/donomo/dbinit.log
prog="Donomo Database"

function init_db_i
{
    source /root/.donomo/db_pwd_root.sh
    source /root/.donomo/db_pwd_donomo.sh

    sentinel=/etc/sysconfig/donomo_${DONOMO_MODE:?}.db
    database=donomo_${DONOMO_MODE:?}
    export USER=donomo
    export LOGNAME=$USER
    export HOME=/home/$USER


    if [[ ! -f "$sentinel" ]]
    then
        echo -n "... $database already loaded"
        return 0
    fi

    mysqladmin -u root password "$ROOT_PASSWORD"

    mysql -u root "-p$ROOT_PASSWORD" mysql <<SQL
create database $database;
grant all on $database.* to '$USER'@'%' identified by '$DATABASE_PASSWORD';
flush privileges;
SQL
    mysqladmin -u root "-p$ROOT_PASSWORD" reload

    su -c "$HOME/bin/application syncdb --noinput" $USER

    if [[ $? -eq 0 ]]
    then
        rm -f "$sentinel"
    fi

    return $?
}

function init_db
{
    init_db_i 2 2>&1 | tee -a "$logfile"
}

case ${1:-blah} in
    start)
    action "Starting: $prog" init_db
        ;;
    stop)
    action "Stopping: $prog" /bin/true
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $(basename $0) start|stop|restart"
        exit 1
        ;;
esac
