#!/bin/sh

# chkconfig: - 99 06
# description: Donomo Archive Processing Pipeline
# pidfile: /var/run/donomo/processor.pid

source /etc/rc.d/init.d/functions

workdir=/var/lib/donomo
pidfile=/var/run/donomo/processors.pid
logfile=/var/log/donomo/processors.log
prog="Donomo Services"

function start
{
    pid=$(pidofproc -p "$pidfile" "$prog")
    if [[ -n "$pid" ]]
    then
	echo -n "- Already running: pid=$pid"
	return 1
    fi

    source /root/.donomo/db_pwd_donomo.sh
    source /root/.donomo/aws.sh

    export USER=donomo
    export LOGNAME=$USER
    export HOME=/home/$USER

    su -c "/home/donomo/bin/processors --daemonize --pidfile=$pidfile --logfile=$logfile --workdir=$workdir" donomo

    return $?
}

case ${1:?} in
    start)
        action "Starting $prog" start
        ;;
    stop)
        action "Stopping $prog" killproc -p $pidfile
        ;;
    status)
	status -p $pidfile "$prog"
	;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $(basename $0) start|stop|restart"
        exit 1
        ;;
esac
