#!/bin/sh

# chkconfig: - 81 81
# description: Donomo Instance Initialization

source /etc/rc.d/init.d/functions

prog="Donomo-Initialization"

##############################################################################
#
# Start the application if it isn't already running
#

function start
{
    source /etc/sysconfig/network
    [[ "${NETWORKING}" = "no" ]] && echo -n "No networking!" && return 1

    echo ""

    echo "Fetching EC2 Meta-Data"
    /opt/rightscale/bin/fetchec2metadata.rb

    echo "Fetching EC2 User-Data"
    /opt/rightscale/bin/fetchec2userdata.rb

    source /var/spool/ec2/meta-data.sh
    source /var/spool/ec2/user-data.sh

    if [[ -d /home/donomo ]]
    then
        ( cd /home/donomo && svn switch --non-interactive --username "${EC2_SUBVERSION_USERNAME:?}" --password "${EC2_SUBVERSION_PASSWORD:?}" "${EC2_SUBVERSION_REPOPATH?}" )
        chown -R root:donomo /home/donomo
        chown -R root:root /home/donomo/init.d
        find /home/donomo -type f -print0 | xargs -0 chmod -f 640
        find /home/donomo -type d -print0 | xargs -0 chmod -f 750
        chmod -R 750 /home/donomo/bin /home/donomo/init.d
    fi
}

##############################################################################
#
#
#

function stop
{
    return 0
}

##############################################################################
#
# Dispatch requested behaviour
#

case ${1:?} in
    start)
        action "Starting $prog" start
        ;;
    stop)
        action "Stopping $prog" stop
        ;;
    status)
        echo "ok"
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $(basename $0) start|stop|status|restart"
        exit 1
        ;;
esac
