#!/bin/sh

# chkconfig: - 97 07
# description: Donomo Database Initialization

source /etc/rc.d/init.d/functions

workdir=/home/donomo
logfile=/var/log/donomo/dbinit.log
initfile=/etc/sysconfig/donomo.db
prog="Donomo DB Init"

function init_db_i
{
    if [[ ! -e $initfile ]]
    then
	return 0
    fi

    source /root/.donomo/db_pwd_root.sh
    source /root/.donomo/db_pwd_donomo.sh

    mysqladmin -u root password "$ROOT_PASSWORD"

    mysql -u root "-p$ROOT_PASSWORD" mysql <<SQL
create database donomo;
grant all on donomo.* to 'donomo'@'%' identified by '$DATABASE_PASSWORD';
flush privileges;
SQL
    mysqladmin -u root "-p$ROOT_PASSWORD" reload

    /home/donomo/bin/application syncdb --noinput 1>&2

    if [[ $? -eq 0 ]]
    then
	rm -f $initfile
    fi

    return $?
}

function init_db
{
    init_db_i 2 >>$logfile
}

case ${1:-blah} in
    start)
	action "Starting: $prog" init_db
        ;;
    stop)
	action "Stopping: $prog" /bin/true
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $(basename $0) start|stop|restart"
        exit 1
        ;;
esac
