#!/bin/sh

# chkconfig: - 99 06
# description: Donomo Archive Web Application
# pidfile: /var/run/donomo/application.pid

source /etc/rc.d/init.d/functions

workdir=/var/lib/donomo
pidfile=/var/run/donomo/application.pid
logfile=/var/log/donomo/application.log
socket=$workdir/fcgi.sock
prog="Donomo Web App"

function start
{
    pid=$(pidofproc -p "$pidfile" "$prog")
    if [[ -n "$pid" ]]
    then
        echo -n "- Already running: pid=$pid"
        return 1
    fi

    source /root/.donomo/db_pwd_donomo.sh
    source /root/.donomo/aws.sh
    su -c "/home/donomo/bin/application runfcgi protocol=fcgi method=prefork daemonize=true pidfile=$pidfile socket=$socket workdir=$workdir outlog=$logfile errlog=$logfile" donomo

    if [[ $? -ne 0 ]]
    then
        return 2
    fi

    chown donomo:nginx $socket
    if [[ $? -ne 0 ]]
    then
        killproc -p $pidfile
        return 3
    fi

    chmod 770 $socket
    if  [[ $? -ne 0 ]]
    then
        killproc -p $pidfile
        return 4
    fi

    return 0
}

case ${1:?} in
    start)
        action "Starting $prog" start
        /sbin/service nginx start
        ;;
    stop)
        /sbin/service nginx stop
        action "Stopping $prog" killproc -p $pidfile        
        ;;
    status)
        status -p $pidfile "$prog"
        /sbin/service nginx status
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $(basename $0) start|stop|restart"
        exit 1
        ;;
esac
