#!/bin/sh

# chkconfig: - 99 06
# description: solr
# pidfile: /var/run/solr/solr.pid

source /etc/rc.d/init.d/functions

workdir=/var/lib/solr
pidfile=/var/run/solr/solr.pid
logfile=/var/log/solr/solr.log
prog="SOLR"

function start
{
    pid=$(pidofproc -p "$pidfile" "$prog")
    if [[ -n "$pid" ]]
    then
	echo -n "- Already running: pid=$pid"
	return 1
    fi

    export USER=solr
    export LOGNAME=$USER
    export HOME=/home/$USER

    mkdir -p /data/solr
    chown solr:solr /data/solr
    chmod 750 /data/solr

    su -c "ln -sf /data/solr /home/solr/solr/data" solr
    su -c "/home/solr/bin/run $logfile $pidfile &" solr

    return $?
}

function stop
{
    killproc -p $pidfile
    return $?
}

case ${1:-blah} in
    start)
	action "Starting $prog" start
        ;;
    stop)
        action "Stopping $prog" stop
        ;;
    status)
	status -p $pidfile $prog
	;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $(basename $0) start|stop|restart"
        exit 1
        ;;
esac
