#!/usr/local/bin/python2.4            

# POST-COMMIT HOOK
#
# The post-commit hook is invoked after a commit.  Subversion runs
# this hook by invoking a program (script, executable, binary, etc.)
# named 'post-commit' (for which this file is a template) with the 
# following ordered arguments:
#
#   [1] REPOS-PATH   (the path to this repository)
#   [2] REV          (the number of the revision just committed)
#
# The default working directory for the invocation is undefined, so
# the program should set one explicitly if it cares.
#
# Because the commit has already completed and cannot be undone,
# the exit code of the hook program is ignored.  The hook program
# can use the 'svnlook' utility to help it examine the
# newly-committed tree.
#
# On a Unix system, the normal procedure is to have 'post-commit'
# invoke other programs to do the real work, though it may do the
# work itself too.
#
# Note that 'post-commit' must be executable by the user(s) who will
# invoke it (typically the user httpd runs as), and that user must
# have filesystem-level permission to access the repository.
#
# On a Windows system, you should name the hook program
# 'post-commit.bat' or 'post-commit.exe',
# but the basic idea is the same.
# 
# The hook program typically does not inherit the environment of
# its parent process.  For example, a common problem is for the
# PATH environment variable to not be set to its usual value, so
# that subprograms fail to launch unless invoked via absolute path.
# If you're having unexpected problems with a hook program, the
# culprit may be unusual (or missing) environment variables.
# 
# Here is an example hook script, for a Unix /bin/sh interpreter.
# For more examples and pre-written hooks, see those in
# the Subversion repository at
# http://svn.collab.net/repos/svn/trunk/tools/hook-scripts/ and
# http://svn.collab.net/repos/svn/trunk/contrib/hook-scripts/


#REPOS="$1"
#REV="$2"

mail_server = 'smtp.gmail.com'
from_email = 'svn@donomo.com'
to_email = 'svn-commits@donomo.com'
mailbox_name = 'svn@donomo.com'
mailbox_password = 'd0n0m0'
trac_path = '/home/alexissmirnov/webapps/trac'


import os
import smtplib
import sys

server = smtplib.SMTP(mail_server, 587)
server.ehlo()
server.starttls()
server.ehlo()
server.login(mailbox_name, mailbox_password)

repository, revision = sys.argv[1:]

# Get the diff from svnlook
#cmd = "svnlook diff %(repository)s -r %(revision)s" % locals()
#diff = os.popen(cmd).read()

log_message=os.popen("svnlook log -r %(revision)s %(repository)s" % locals()).read()
author=os.popen("svnlook author -r %(revision)s %(repository)s" % locals()).read()


msg = (
"To: %(to_email)s\r\n"
"From: %(from_email)s\r\n"
"Subject: Changeset [%(revision)s] by %(author)s\r\n"
"\r\n"
"Changeset [%(revision)s] by %(author)s\r\n"
"\r\n\r\n"
"%(log_message)s"
"\r\n"
"Details: http://trac.donomo.com/changeset/%(revision)s\r\n"
)

msg = msg % locals()

server.sendmail(from_email, to_email, msg)
server.close()

# update trac
pch = 'export PYTHONPATH=/usr/local/lib/svn-python/:/home/alexissmirnov/webapps/trac/lib/python2.4/Trac-0.11-py2.4.egg:$PYTHONATH;./trac-post-commit-hook -p "%(trac_path)s" -r "%(revision)s" -u "%(author)s" -m "%(log_message)s"' % locals()
os.popen(pch)

